# Generated by Django 2.1.2 on 2018-10-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotas',
            name='estado',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
