# Generated by Django 2.1.2 on 2018-10-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0003_registrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrado',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='registrado',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='registrado',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='registrado',
            name='region',
        ),
        migrations.RemoveField(
            model_name='registrado',
            name='tipoVivienda',
        ),
        migrations.AddField(
            model_name='registrado',
            name='apellidos',
            field=models.CharField(max_length=23, null=True),
        ),
        migrations.AddField(
            model_name='registrado',
            name='nombres',
            field=models.CharField(max_length=23, null=True),
        ),
    ]
